// Cars Makes
const GET_CARS_MAKES_SUCCESS = "GET_CARS_MAKES_SUCCESS";
const GET_CARS_MAKES_REQUEST = "GET_CARS_MAKES_REQUEST";
const GET_CARS_MAKES_ERROR = "GET_CARS_MAKES_ERROR";
// Cars Models
const GET_CARS_MODELS_SUCCESS = "GET_CARS_MODELS_SUCCESS";
const GET_CARS_MODELS_REQUEST = "GET_CARS_MODELS_REQUEST";
const GET_CARS_MODELS_ERROR = "GET_CARS_MODELS_ERROR";
// Selected Car
const GET_SELECTED_CARS_SUCCESS = "GET_SELECTED_CARS_SUCCESS";
const GET_SELECTED_CARS_REQUEST = "GET_SELECTED_CARS_REQUEST";
const GET_SELECTED_CARS_ERROR = "GET_SELECTED_CARS_ERROR";

const CLEAN = "CLEAN";

const Types = {
    // Cars Makes
    GET_CARS_MAKES_SUCCESS,
    GET_CARS_MAKES_REQUEST,
    GET_CARS_MAKES_ERROR,
    // Cars Models
    GET_CARS_MODELS_SUCCESS,
    GET_CARS_MODELS_REQUEST,
    GET_CARS_MODELS_ERROR,
    // Selected Car
    GET_SELECTED_CARS_SUCCESS,
    GET_SELECTED_CARS_REQUEST,
    GET_SELECTED_CARS_ERROR,
    CLEAN
}

export default Types;